/* [SUPERSEDED] The app icon is now generated by design/icon/appicon.gen.mjs (the isometric irori).
   This file is kept as an archive of the previous flat # icon and for comparing candidates.

   SVG sources for the generated icons. All variants share the same "paper card" base: the macOS icon
   grid (1024 canvas, 824 body, 100 margin), continuous corners (superellipse n=5), a paper gradient
   lighter at the top and darker at the bottom, a very faint inner stroke, and a soft drop shadow.
   They differ only in what is drawn on top.

   ── What the shape means ─────────────────────────────────────
   An irori (囲炉裏) is the square sunken hearth set into the floor of a traditional Japanese house.
   The 井 character depicts its igeta frame (the igeta, or well-curb, pattern is itself a very old
   family crest), and this 井 happens to be `#` in Markdown.
   So the icon has just two layers: the faded igeta frame = the markup that is always there; the warm
   spot in the middle of the frame = the fire, which is also the cursor, the place you are writing.
   Colors follow the app itself: paper background, #C3B7A4 markers, #A27B5C warm brown. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url));

// Superellipse (continuous corners); closer to the macOS icon outline than rx rounded corners
function squircle(cx, cy, a, n = 5, steps = 256) {
  const pts = [];
  for (let i = 0; i < steps; i++) {
    const t = (i / steps) * Math.PI * 2;
    const c = Math.cos(t), s = Math.sin(t);
    const x = cx + a * Math.sign(c) * Math.pow(Math.abs(c), 2 / n);
    const y = cy + a * Math.sign(s) * Math.pow(Math.abs(s), 2 / n);
    pts.push(`${x.toFixed(2)},${y.toFixed(2)}`);
  }
  return `M${pts.join('L')}Z`;
}
const BODY = squircle(512, 512, 412);

const ACCENT = '#A27B5C';
const TOK = '#C3B7A4';

const base = (inner, extraDefs = '') => `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
  <defs>
    <linearGradient id="paper" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#FCF9F3"/>
      <stop offset="1" stop-color="#EFE6D8"/>
    </linearGradient>
    <filter id="shadow" x="-20%" y="-20%" width="140%" height="140%">
      <feDropShadow dx="0" dy="14" stdDeviation="18" flood-color="#5A3D22" flood-opacity="0.22"/>
    </filter>
    <clipPath id="clip"><path d="${BODY}"/></clipPath>
    ${extraDefs}
  </defs>
  <path d="${BODY}" fill="url(#paper)" filter="url(#shadow)"/>
  <g clip-path="url(#clip)">${inner}</g>
  <path d="${BODY}" fill="none" stroke="${ACCENT}" stroke-opacity="0.16" stroke-width="3"/>
</svg>`;

/* Igeta: two vertical and two horizontal strokes enclosing a hearth cell in the center.
   half   — how far the strokes reach from the center (sets the size of the whole glyph)
   gap    — half-width of the center cell (sets the hearth size)
   w      — stroke width
   slant  — slant of the vertical strokes (0 = upright igeta pattern; >0 looks more like a
            handwritten Markdown #)
   op     — opacity of the whole group. Note it is set on the <g>, not on each line: at the four
            crossings two strokes overlap, and stroke-opacity would stack into four darker squares. */
const igeta = (stroke, { half = 232, gap = 92, w = 36, slant = 0, op = 1 } = {}) => `
    <g stroke="${stroke}" opacity="${op}" stroke-width="${w}" stroke-linecap="round" fill="none">
      <line x1="${512 - gap + slant}" y1="${512 - half}" x2="${512 - gap - slant}" y2="${512 + half}"/>
      <line x1="${512 + gap + slant}" y1="${512 - half}" x2="${512 + gap - slant}" y2="${512 + half}"/>
      <line x1="${512 - half}" y1="${512 - gap}" x2="${512 + half}" y2="${512 - gap}"/>
      <line x1="${512 - half}" y1="${512 + gap}" x2="${512 + half}" y2="${512 + gap}"/>
    </g>`;

/** Soft glow at the hearth's center. r reaches a bit past the center cell's diagonal so the corners don't cut off abruptly. */
const hearthGlow = (r = 200) => `<circle cx="512" cy="512" r="${r}" fill="url(#ember)"/>`;

const emberGrad = (op = 0.32) => `<radialGradient id="ember">
      <stop offset="0" stop-color="#C98A4E" stop-opacity="${op}"/>
      <stop offset="0.55" stop-color="${ACCENT}" stop-opacity="${(op * 0.32).toFixed(3)}"/>
      <stop offset="1" stop-color="${ACCENT}" stop-opacity="0"/>
    </radialGradient>`;
const caretGrad = `<linearGradient id="caret" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#AF8868"/><stop offset="1" stop-color="#946E50"/></linearGradient>`;

/** Hearth fire: the solid shape in the center cell + the glow spilling out. The one-step-deeper orange
    (#C2702F) is the only highly saturated color in the image, so even at 32px you can tell "there's a
    bit of fire in the middle". */
const fire = (kind) => {
  if (kind === 'square') return `<rect x="458" y="458" width="108" height="108" rx="30" fill="url(#fire)"/>`;
  if (kind === 'caret') return `<rect x="489" y="428" width="46" height="168" rx="23" fill="url(#fire)"/>`;
  return '';
};
const fireGrad = `<linearGradient id="fire" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#D2853B"/><stop offset="1" stop-color="#B25F27"/>
    </linearGradient>`;

const variants = {
  // A: warm brown wooden frame + a burning ember at the center. Most robust at small sizes: a # with a bit of fire in the middle
  'a-frame-ember': base(
    `${hearthGlow(210)}
    ${igeta(ACCENT, { op: 0.85 })}
    ${fire('square')}`,
    emberGrad(0.5) + fireGrad,
  ),
  // B: same frame, with a cursor at the center instead — "the place you're writing is the fire"
  'b-frame-caret': base(
    `${hearthGlow(210)}
    ${igeta(ACCENT, { op: 0.85 })}
    ${fire('caret')}`,
    emberGrad(0.5) + fireGrad,
  ),
  // C: frame fades to the marker color (the "faded" look of source decorations); all the weight goes to the fire
  'c-pale-frame-ember': base(
    `${hearthGlow(215)}
    ${igeta(TOK)}
    ${fire('square')}`,
    emberGrad(0.55) + fireGrad,
  ),
  // D: thinner frame, larger glyph, fire reduced to a layer of glow (the quietest version)
  'd-quiet': base(
    `${hearthGlow(200)}
    ${igeta(ACCENT, { w: 30, half: 244, gap: 96, op: 0.8 })}
    <rect x="470" y="470" width="84" height="84" rx="24" fill="url(#fire)" fill-opacity="0.9"/>`,
    emberGrad(0.42) + fireGrad,
  ),
  // E: slanted vertical strokes — closer to Markdown's #, further from the igeta pattern
  'e-slant': base(
    `${hearthGlow(210)}
    ${igeta(ACCENT, { slant: 22, op: 0.85 })}
    ${fire('square')}`,
    emberGrad(0.5) + fireGrad,
  ),
  // The earlier "faint #, strong cursor" icon, kept only as a reference for side-by-side comparison
  'prev-v011': base(
    `<g stroke="#BBAC96" stroke-width="32" stroke-linecap="round">
      <line x1="352" y1="392" x2="330" y2="632"/>
      <line x1="446" y1="392" x2="424" y2="632"/>
      <line x1="290" y1="472" x2="488" y2="472"/>
      <line x1="282" y1="556" x2="480" y2="556"/>
    </g>
    <rect x="596" y="352" width="42" height="320" rx="21" fill="url(#caret)"/>`,
    caretGrad,
  ),
};

fs.mkdirSync(path.join(here, 'out/variants'), { recursive: true });
for (const [name, svg] of Object.entries(variants)) {
  fs.writeFileSync(path.join(here, 'out/variants', name + '.svg'), svg);
  console.log('› out/variants/' + name + '.svg');
}

/* ---- Final ----
   A with its proportions refined once more: the frame a touch thinner, a more visible clearance
   around the hearth (the fire doesn't touch the frame), and the glow raised so it still carries
   some warmth at 32px. This one is the source of src-tauri/icons/:
       node design/icon/gen.mjs && node design/icon/render.mjs out/irori.svg
       npx tauri icon design/icon/out/irori.png */
const FINAL = base(
  `${hearthGlow(224)}
    ${igeta(ACCENT, { w: 34, half: 236, gap: 94, op: 0.85 })}
    <rect x="462" y="462" width="100" height="100" rx="28" fill="url(#fire)"/>`,
  emberGrad(0.55) + fireGrad,
);
fs.writeFileSync(path.join(here, 'out/irori.svg'), FINAL);
console.log('› out/irori.svg (previous final)');
